### ISSUE TITLE
Documentation has no favicon or tab title

### ISSUE THREAD

**Issue by Kenny2github** [ScratchVerifier/ScratchVerifier#23]
@smileycreations15 assigning you to choose favicon

**Comment by smileycreations15** [comment]
@Kenny2github Ok!

**Comment by VFDan** [comment]
Should we just keep the same favicon?

**Comment by smileycreations15** [comment]
@VFDan yes.

**Comment by VFDan** [comment]
I'll add the favicon then.

**Comment by smileycreations15** [comment]
Create a repo called scratchverifier.github.io then upload the file there @VFDan

**Comment by VFDan** [comment]
@smileycreations15 What do you mean? I'm not at home so I don't have the file on me, sorry.

**Comment by smileycreations15** [comment]
@VFDan I can do it thrn

**Comment by VFDan** [comment]
ok
