### ISSUE TITLE
The logs are ordered last to first.

### ISSUE THREAD

**Issue by smileycreations15** [ScratchVerifier/ScratchVerifier#30]
Is this a bug?

**Comment by VFDan** [comment]
I don't think so.

**Comment by smileycreations15** [comment]
@VFDan I assigned Ken because Ken will know it better.

**Comment by Kenny2github** [comment]
It was a deliberate design decision... Wiki recent changes are ordered newest to oldest, because it's recent events so most recent comes first. Why would logs be any different?
