### ISSUE TITLE
SSL?

### ISSUE THREAD

**Issue by AfterNetwork** [ScratchVerifier/ScratchVerifier#31]

**Comment by smileycreations15** [comment]
This has been placed into the backlog.

**Comment by smileycreations15** [comment]
@AfterNetwork

**Comment by AfterNetwork** [comment]
> @AfterNetwork

U DELETED AFP

**Comment by smileycreations15** [comment]
@AfterNetwork Please do not go off-topic

**Comment by AfterNetwork** [comment]
why did u delete afp

**Comment by smileycreations15** [comment]
@AfterNetwork Please do not go off-topic + Please talk in private chat.

**Comment by AfterNetwork** [comment]
why did u delete afp

**Comment by smileycreations15** [comment]
@AfterNetwork Please do not go off-topic. Last time.

**Comment by Kenny2github** [comment]
SSL is probably a good idea considering we do require authorization :P but it may be difficult. I'll call this low-priority.

**Comment by Kenny2github** [comment]
I've found a way to do this! I now have a reverse proxy with Apache and Let's Encrypt running at https://scratchverifier.ddns.net/site

**Comment by Semisol** [comment]
Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

rip

**Comment by Semisol** [comment]
ken is trying to fix it rn

**Comment by Semisol** [comment]
It is up at  https://scratchverifier.ddns.net/site
