### ISSUE TITLE
500 on POST /verify/{username}

### ISSUE THREAD

**Issue by Kenny2github** [ScratchVerifier/ScratchVerifier#35]
```
Traceback (most recent call last):
  File "ScratchVerifier/backend/server.py", line 63, in errors
    return await handler(request)
  File "ScratchVerifier/backend/server.py", line 189, in verified
    if await self._verified(client_id, username):
  File "ScratchVerifier/backend/server.py", line 159, in _verified
    code = await self.db.get_code(client_id, username)
  File "ScratchVerifier/backend/db.py", line 166, in get_code
    if time.time() > row['expiry']:
IndexError: No item with that key
```
@smileycreations15 what were you doing when this happened? (1:09 AM HKT)

**Comment by smileycreations15** [comment]
I was making a project with ScratchVerifier

**Comment by Kenny2github** [comment]
Could you provide steps to reproduce that error? (You have access to the error log, so use that to figure out whether your steps to reproduce succeed in reproducing the error.)

**Comment by micahlt** [comment]
@Kenny2github @smileycreations15 This is happening to me too.  Is ScratchVerifier broken currently?

**Comment by smileycreations15** [comment]
No. Let me check. I found out that you haven't supplied credentials in any way. @micahlt

**Comment by micahlt** [comment]
@smileycreations15 Credentials?  Are you referring to my auth token?  It's there.  If you want to you can check my code: 
```javascript
let auth = 'Basic (my key is here)';
let url = 'https://cors-anywhere.herokuapp.com/scratchverifier.ddns.net:8888/verify/' + document.getElementById('usr').value;
      fetch(url, {
          method: 'PUT',
          mode: 'cors',
          headers: {
            'Authorization': auth
          }
        })
        .then((response) => {
          return response.json();
        })
        .then((data) => {
          console.log(data);
          document.getElementById('code').innerText = data["code"];
        });
```

**Comment by smileycreations15** [comment]
Not that.

**Comment by micahlt** [comment]
Then what do you mean?  I'm confused- I believe I'm following the API's directions correctly.

**Comment by smileycreations15** [comment]
```js
let id = "<id for api>", token = "<token for api>"
let url = 'https://cors-anywhere.herokuapp.com/scratchverifier.ddns.net:8888/verify/' + document.getElementById('usr').value;
      fetch(url, {
          method: 'PUT',
          mode: 'cors',
          headers: {
            'Authorization': "Basic " + btoa(id+":"+token)
          }
        })
        .then((response) => {
          return response.json();
        })
        .then((data) => {
          console.log(data);
          document.getElementById('code').innerText = data["code"];
        });
```

**Comment by micahlt** [comment]
Oh, okay!  I wasn't aware of that.  What's the ID for API?  Is that the session ID?

**Comment by smileycreations15** [comment]
Ok.

**Comment by Kenny2github** [comment]
It shouldn't be 500ing on invalid auth, though - I'll look into that.

**Comment by Kenny2github** [comment]
More concrete example - modchat.micahlindley.com apparently [uses](https://github.com/micahlt/modchat/blob/master/index.js#L86-L111) SV and it's failed on that many times, all with the same traceback:
```
Traceback (most recent call last):
  File "ScratchVerifier/backend/server.py", line 63, in errors
    return await handler(request)
  File "ScratchVerifier/backend/server.py", line 189, in verified
    if await self._verified(client_id, username):
  File "ScratchVerifier/backend/server.py", line 159, in _verified
    code = await self.db.get_code(client_id, username)
  File "ScratchVerifier/backend/db.py", line 166, in get_code
    if time.time() > row['expiry']:
IndexError: No item with that key
```
However, they apparently [aren't seeing any errors on their side](https://scratch.mit.edu/users/-Zix-/#comments-79151670).

**Comment by Kenny2github** [comment]
So I think this might be a race condition. It might be possible for this to happen:
1. [`get_code`](https://github.com/ScratchVerifier/ScratchVerifier/blob/develop/backend/db.py#L160) is called
2. [`client_matches`](https://github.com/ScratchVerifier/ScratchVerifier/blob/develop/backend/db.py#L28) is called
3. `get_code` [SELECTs `code, expiry`](https://github.com/ScratchVerifier/ScratchVerifier/blob/develop/backend/db.py#L161-L162)
4. `client_matches` [SELECTs `client_id`](https://github.com/ScratchVerifier/ScratchVerifier/blob/develop/backend/db.py#L29-L30) **before `get_code` can call `db.fetchone()`**
5. `get_code` [calls `db.fetchone()`](https://github.com/ScratchVerifier/ScratchVerifier/blob/develop/backend/db.py#L163) **and is returned the results of the `SELECT client_id`**
6. `client_matches` [calls `db.fetchone()`](https://github.com/ScratchVerifier/ScratchVerifier/blob/develop/backend/db.py#L31) and is returned a guaranteed `None` (side effect that causes no errors but probably causes problems too)

I have attempted to counter this by introducing a lock around all `SELECT` db queries. I haven't opened a pull for this - I've done it in live production, because Modchat is still our best source of test cases. Hopefully later today (my time) people will become active on Modchat and we'll see from error logs whether locks fixed the problem.
