### ISSUE TITLE
How can I deploy on my own server ?

### ISSUE THREAD

**Issue by locness3** [ScratchVerifier/ScratchVerifier#37]
You should add info to the readme.

**Comment by smileycreations15** [comment]
@locness3 We already have docs and a website.

**Comment by smileycreations15** [comment]
Also how to deploy:

**Comment by smileycreations15** [comment]
First, clone the repository. (`git clone https://github.com/ScratchVerifier/ScratchVerifier`)
Then, cd into the repository (`cd ScratchVerifier`)
Then edit the `config.json` file on the folder, with this content:
```json
{"port":80,"discord-hook":"","name":"","hook-secret":""}
```
After that, install dependencies (`pip3 install -r requirements.txt`)
Then you can start the server :) (`python3 backend`)

**Comment by smileycreations15** [comment]
@locness3

**Comment by locness3** [comment]
Ok, thanks. You should add that to the readme.

**Comment by smileycreations15** [comment]
:)

**Comment by locness3** [comment]
?

**Comment by smileycreations15** [comment]
@locness3 I will.

**Comment by locness3** [comment]
ok, thanks :)

**Comment by locness3** [comment]
Why closed ? @Kenny2github

**Comment by Kenny2github** [comment]
The question was answered. Adding instructions to the readme would not be directly related to the issue.

**Comment by locness3** [comment]
Ok, thanks.
