### ISSUE TITLE
Bensound

### ISSUE THREAD

**Issue by ConvexPolygonGH** [ScratchVerifier/ScratchVerifier#40]
For the intro video, the music is Summer by Bensound. Do you have a license, because without one you have to give credit.

**Comment by AfterNetwork** [comment]
> For the intro video, the music is Summer by Bensound. Do you have a license, because without one you have to give credit. 

err. does it apply to fair use?

**Comment by smileycreations15** [comment]
Oh, sorry. I forgot. I am also not sure @AfterNetwork.

**Comment by Accio1** [comment]
According to https://www.bensound.com/licensing :
You can use Bensound's music available under the Free License (with the black download button) in your multimedia project (online videos, **websites**, animations, etc.) for free as long as you credit Bensound.com. Examples of proper way to credit us: "Music: https://www.bensound.com/royalty-free-music or "Music: « Song Title » from Bensound.com"

**Comment by Accio1** [comment]
I can add Bensound to the credits page so that they are given the credit that they deserve.
