### ISSUE TITLE
The credits page is hidden

### ISSUE THREAD

**Issue by Accio1** [ScratchVerifier/ScratchVerifier#42]
There is currently no way to access the credits page, other than by manually typing "http://scratchverifier.ddns.net:8888/site/credits" into the URL bar. I propose that there should be a link to the credits page either in the header or the footer of the homepage so that it's more visible. 

I can add it to either the header or the footer, I just need to know which one to add it to.

**Comment by Accio1** [comment]
@smileycreations15

**Comment by smileycreations15** [comment]
Currently unknown why. But footer is fine.

**Comment by Kenny2github** [comment]
Not really unknown lol - it was just never added. Footer is fine, agreed.

**Comment by Accio1** [comment]
There currently is no footer. Do you want me to create one? If so, what else should be in it? And should it only be on the homepage or all the pages?

**Comment by smileycreations15** [comment]
Homepage only.
Credits, the license, and docs link.
