### ISSUE TITLE
ScratchLink1

### ISSUE THREAD

**Issue by geographix** [ScratchVerifier/ScratchVerifier#44]
ScratchLink1 is a platform on which scratchers can collaborate and run shops. We are looking into using ScratchVerifier as our signing in method. Could we have more information about integrating scratch verifier into our platform? We will also need a sign up feature so we can log users on the platform.
Thanks, the ScratchLink1 Team

**Comment by smileycreations15** [comment]
Sure! The documentation is available at: http://scratchverifier.ddns.net:8888/docs/
You can sign up at: http://scratchverifier.ddns.net:8888/site/

**Comment by geographix** [comment]
Thanks! I will contact you if further needed.

**Comment by smileycreations15** [comment]
No problem. There are no rate limits right now, but I would recommend not making too many requests, to prevent overloading of the server.

**Comment by geographix** [comment]
okay. we'll probably only need for signing in and logging users into our api. We've got ConvexPolygon working on our backend and I think those are trusted hands

**Comment by smileycreations15** [comment]
Ok, I am closing this, tell if you have any issues and I will reopen it.
