### ISSUE TITLE
Servers down

### ISSUE THREAD

**Issue by micahlt** [ScratchVerifier/ScratchVerifier#48]
The ScratchVerifier servers appear to be down.  All API requests and pings just time out.

**Comment by Kenny2github** [comment]
My pi is down. Investigating.

**Comment by micahlt** [comment]
@Kenny2github Ah, okay.  Thanks!

**Comment by Kenny2github** [comment]
Resolved - turns out my DNS hadn't updated in a while and my IP changed. What I thought was my pi not responding was actually me failing to SSH through the domain.
