### ISSUE TITLE
Admin Panel

### ISSUE THREAD

**Issue by Semisol** [ScratchVerifier/ScratchVerifier#53]
Just something so we can manage rate limits, and also can display logs for a user and might help blocking abusers from the platform but this is just a suggestion and I don't think we 100% need this.

Might also be used for the admin contact/key unlock requests in #52.

**Comment by Semisol** [comment]
@Accio1 Can you send the finished product soon?

**Comment by Semisol** [comment]
(HTML)

**Comment by Accio1** [comment]
I just have the last page left and then I can send it. The first and second pages are done and responsive.

**Comment by Semisol** [comment]
Screenshots? @Accio1

**Comment by Accio1** [comment]
@Semisol 

Page One (Computer)
![ScratchVerifierAdmin1a](https://user-images.githubusercontent.com/48496940/90988650-7e7e8d00-e562-11ea-8340-0469aaf16e97.png)

Page One (Mobile)
![ScratchVerifierAdmin1b](https://user-images.githubusercontent.com/48496940/90988665-9524e400-e562-11ea-9253-c4657886ec41.png)

Page Two (Computer)
![ScratchVerifierAdmin2a](https://user-images.githubusercontent.com/48496940/90988673-9f46e280-e562-11ea-8e77-38ca3fc05bf3.png)

Page Two (Mobile)
![ScratchVerifierAdmin2b](https://user-images.githubusercontent.com/48496940/90988684-aff75880-e562-11ea-8353-3d2843bb59c5.png)

**Comment by Semisol** [comment]
ty

**Comment by Semisol** [comment]
also add a fetch button to the logs thing @Accio1 forgot that on the design

**Comment by Accio1** [comment]
@Semisol Where should the fetch button go?

**Comment by Semisol** [comment]
after the inputs

**Comment by Accio1** [comment]
Okay. The inputs will have to be smaller to make space for the button.

**Comment by Semisol** [comment]
Okay.

**Comment by Accio1** [comment]
@Semisol The last page is done.

Page 3 (computer)
![ScratchVerifierAdmin3a](https://user-images.githubusercontent.com/48496940/91065994-25186b80-e5ff-11ea-8769-bc4da52ad626.png)

Page 3 (mobile)
![ScratchVerifierAdmin3b](https://user-images.githubusercontent.com/48496940/91065997-26499880-e5ff-11ea-9df5-bee2f0ea831f.png)

**Comment by Semisol** [comment]
seems good @Accio1

**Comment by Accio1** [comment]
Okay. There is no JS yet, just HTML and CSS because I wasn't quite sure what you wanted everything to do. Do you want me to add any JS?

**Comment by Semisol** [comment]
I will do JS when @Kenny2github does the API. (Yeah, that was an intentional ping.)

**Comment by Accio1** [comment]
Okay. Do you want me to submit a PR with these three pages?

**Comment by Semisol** [comment]
Yes, path should be /public/admin/page

**Comment by Semisol** [comment]
access_denied.html
dashboard.html
user.html

**Comment by Semisol** [comment]
(I will do some JS things in user.html.)

**Comment by Accio1** [comment]
Also, should I use the regular favicon on the pages or will a new one be created specifically for the Admin Panel?

**Comment by Semisol** [comment]
No changes in favicon.

**Comment by Accio1** [comment]
Okay.

**Comment by Semisol** [comment]
We still haven't implemented the JS.

**Comment by Kenny2github** [comment]
Remaining to do is to implement the JS handling the endpoints in #55.

**Comment by Semisol** [comment]
[`admin-panel-issues-#55-#53`](https://github.com/ScratchVerifier/ScratchVerifier/tree/admin-panel-issues-%2355-%2353)
