### ISSUE TITLE
Create admin panel API endpoints and modify session endpoints

### ISSUE THREAD

**Issue by Kenny2github** [ScratchVerifier/ScratchVerifier#55]
In all the below, all integers are examples and arbitrary

## Changes to existing endpoints
- [x] POST `/users/{username}/login`: Raise 403 if `username` is banned
- [x] POST `/users/{username}/finish-login`: Instead of returning JSON with the session ID, set it as a cookie
- [x] POST `/users/{username}/finish-login`: Return `{"admin": true}` if logged in user is admin, `{"admin": false}` otherwise.
- [x] POST `/users/{username}/logout`: Instead of taking session ID as a query variable, pass it as a cookie
- [x] GET, PUT, PATCH, DELETE `/session/{session ID}`: change to METHOD `/session` with session ID as a cookie
- [x] POST `/session/{session ID}/logout`: change to POST `/session/logout` with session ID as a cookie

## Authentication and formats for new endpoints
- [x] All of the endpoints in the next session must have the session ID passed in the same way as the `/session` endpoints - as a cookie. The POST `/users/{username}/finish-login` endpoint will have a Set-Cookie header with the session ID.
- [x] Invalid authentication results in a 401 response.
- [x] For requests that need bodies, that body must be `application/json`-encoded.
- [x] Any missing fields or malformatted data result in a 400 response.

### Rate limits

- [x] GET `/admin/ratelimits`: gets all current ratelimits
  - HTTP statuses:
    - [x] 200 OK: returns **list of** Ratelimit objects like below
    - [x] 401 Unauthorized: invalid or no `session` in cookies
```json
{"username": "UserNameToLimit", "limit": 30}
```

- [x] PATCH `/admin/ratelimits`: sets ratelimits for multiple clients at once
  - HTTP statuses:
    - [x] 204 No Content: success
    - [x] 401 Unauthorized: invalid or no `session` in cookies
  - [x] Multiple users' limits can be specified at once; only those specified will be updated or added.
  - [x] Request body is a list of (full) Ratelimit objects like above

- [x] GET `/admin/ratelimits/{username}`: gets ratelimit for a specific user
  - HTTP statuses:
    - [x] 200 OK: returns partial Ratelimit object like below
    - [x] 400 Bad Request: username invalid by Scratch standards
    - [x] 401 Unauthorized: invalid or no `session` in cookies
    - [x] 404 Not Found: no ratelimit set for that user
```json
{"limit": 30}
```

- [x] POST `/admin/ratelimits/{username}`: sets ratelimit for a specific user
  - HTTP statuses:
    - [x] 204 No Content: success
    - [x] 400 Bad Request: username invalid by Scratch standards or data had incorrect types
    - [x] 401 Unauthorized: invalid or no `session` in cookies
  - [x] Request body is a partial Ratelimit object like above
  - [x] Nonexistent users can be set anyway, to preemptively set ratelimits for that user if they create clients

### Banning users

- [x] GET `/admin/bans`: gets bans currently in force
  - HTTP statuses:
    - [x] 200 OK: returns **list of** Ban objects like below
    - [x] 401 Unauthorized: invalid or no `session` in cookies
  - [x] `expiry` is in Unix epoch seconds, or `null` if permanent
```json
{"username": "ScratchUsername", "expiry": 1234567890}
```

- [x] PATCH `/admin/bans`: bans multiple users (equivalent to previous endpoint on each entry)
  - HTTP statuses:
    - [x] 204 No Content: success
    - [x] 401 Unauthorized: invalid or no `session` in cookies
  - [x] Request body is a **list of** Ban objects like above.
  - [x] Invalid entries are ignored.
  - [x] Also deletes all clients they might have already registered.

- [x] GET `/admin/bans/{username}`: gets ban info for a user
  - HTTP statuses:
    - [x] 200 OK: returns partial Ban object like below
    - [x] 400 Bad Request: invalid username by Scratch standards
    - [x] 401 Unauthorized: invalid or no `session` in cookies
    - [x] 404 Not Found: specified username is not banned or doesn't own a client
```json
{"expiry": 1234567890}
```

- [x] POST `/admin/bans/{username}`: bans a user
  - HTTP statuses:
    - [x] 204 No Content: success
    - [x] 400 Bad Request: invalid username by Scratch standards or expiry is in the past, or data had incorrect types
    - [x] 401 Unauthorized: invalid or no `session` in cookies
  - [x] Request body is a partial Ban object like above.
  - [x] Also deletes all clients they might have already registered.

- [x] DELETE `/admin/bans/{username}`: unbans a user
  - HTTP statuses:
    - [x] 204 No Content: success
    - [x] 400 Bad Request: invalid username by Scratch standards
    - [x] 401 Unauthorized: invalid or no `session` in cookies

### Audit logs
- [x] GET `/admin/logs`: gets audit logs from newest to oldest
  - Takes query params:
    - [x] `limit=n` to return at most `n` logs. `n` is 100 by default but has no limit.
    - [x] `start=n` to return logs before (not including) log ID `n`.
    - [x] `end=n` to return logs after (not including) log ID `n`.
    - [x] `before=n` to return logs before (and including) Unix time `n`.
    - [x] `after=n` to return logs after (and including) Unix time `n`.
    - [x] `username=name` to return logs *performed by* `name`.
    - [x] `type=n` to return logs of type `n`.
  - HTTP statuses:
    - [x] 200 OK: returns **list of** AuditLog objects like below
    - [x] 400 Bad Request: `start` is after `end`, `before` is after `after`, or `type` is invalid
    - [x] 401 Unauthorized: invalid or no `session` in cookies
  - Log types are:
    - [x] 1 for ban
    - [x] 2 for ratelimit change
    - [x] 3 for unban
```json
{
  "id": 123,
  "username": "performer",
  "time": 1234567890,
  "type": 1,
  "data": "{\"username\": \"ScratchUsername\", \"expiry\": 1234567890}"
}
```

- [x] GET `/admin/logs/{log ID}`: gets specific log by ID
  - HTTP statuses:
    - [x] 200 OK: returns single AuditLog object like above
    - [x] 401 Unauthorized: invalid or no `session` in cookies
    - [x] 404 Not Found: no log with that ID

### Other
- [x] GET `/admin/client/{client ID}`: gets info about a client
  - HTTP statuses:
    - [x] 200 OK: returns a Client object like below
    - [x] 401 Unauthorized: invalid or no `session` in cookies
    - [x] 404 Not Found: no client with that ID
  - [x] `"ratelimit": null` means no ratelimit is set. The default is still 30.
```json
{
  "client_id": 1234567890,
  "token": "partially censored **************",
  "username": "UserNameOfClientOwner",
  "ratelimit": 30,
  "banned": false
}
```

**Comment by Semisol** [comment]
#53

**Comment by Semisol** [comment]
Closes #53

**Comment by Semisol** [comment]
Add /admin/check, to check if the session is an admin token so I can redirect to /site/admin/access_denied if its not valid.

**Comment by Kenny2github** [comment]
Nah, `/users/{username}/finish-login` will include an `"admin": true` attribute if the user is an admin.

**Comment by Semisol** [comment]
Okay.

**Comment by Semisol** [comment]
Also, the rate limits are intended to be user-to-user basis.

**Comment by Semisol** [comment]
Also will the /usage API change to show usernames or?

**Comment by Semisol** [comment]
https://github.com/ScratchVerifier/ScratchVerifier/tree/admin-panel-issues-%2355-%2353

**Comment by Kenny2github** [comment]
No, `/admin/client` can get username and other information instead.

**Comment by Semisol** [comment]
Okay.

**Comment by Kenny2github** [comment]
All tests have passed for this feature!
