### ISSUE TITLE
Create UI

### ISSUE THREAD

**Issue by Kenny2github** [ScratchVerifier/ScratchVerifier#6]
- [x] Log in via the API we're creating
- [x] If no client ID + token is registered with this account yet, offer to create one
- [x] If a client ID + token is registered with this account:
  - [x] Show client ID
  - [x] Show masked (starred-out) token
  - [x] Offer button to regenerate token
  - [ ] ~~Offer button to unmask token~~
  - [x] Offer button to copy token
  - [x] Offer button to delete account
----
Assigning @smileycreations15 because I don't know who's actually part of the @ScratchVerifier/frontend team.

**Comment by smileycreations15** [comment]
Closing, done
