### ISSUE TITLE
Fix existing tests

### ISSUE THREAD

**Issue by Kenny2github** [ScratchVerifier/ScratchVerifier#60]
A lot of changes were made in #56 and the tests need to be updated for them.
- [x] Sessions are now in cookies
- [x] POST `/users/{username}/finish-login` returns Admin object, not Session
- [x] GET `/usage` with parameters was never tested fsr

(There's more; I will update as I find it.)

**Comment by Kenny2github** [comment]
oops, meant to close

**Comment by Semisol** [comment]
ok
