### ISSUE TITLE
[FR] Improve UI

### ISSUE THREAD

**Issue by sargent-coding** [ScratchVerifier/ScratchVerifier#65]
**Is your feature request related to a problem? Please describe.**
Poor UI

**Describe the solution you'd like**
Better UI

**Describe alternatives you've considered**
null

**Additional context**
I can help.

**Comment by Accio1** [comment]
Please provide more information. What makes the UI poor? What could be done to improve?

**Comment by sargent-coding** [comment]
It looks like you used some free Powerpoint format. If you want to see some of my art:
[Sargent Coding](https://www.saco.ml)
[Scratch](https://scratch.mit.edu/users/speedblocks)

**Comment by Semisol** [comment]
Please give us constructive criticism.
This does not help us fix this problem, just by saying "bad UI" then asking so you can contribute.
If you want to do it yourself, fork the repo, change what you want, we will review it and merge it if we want to.

**Comment by Semisol** [comment]
> It looks like you used some free Powerpoint format. If you want to see some of my art:
> [Sargent Coding](https://www.saco.ml)
> [Scratch](https://scratch.mit.edu/users/speedblocks)

Also that is not true, I just had a very simple design idea when this was created instead.
Also your website was an IFrame'd wix site with the top bar hiddden, so I would not consider that HTML skills.

**Comment by Semisol** [comment]
@sargent-coding (just in case)

**Comment by Semisol** [comment]
Would like more information on what can be added.

**Comment by ElliotDoesCode** [comment]
> **Is your feature request related to a problem? Please describe.**
> Poor UI
> 
> **Describe the solution you'd like**
> Better UI
> 
> **Describe alternatives you've considered**
> null
> 
> **Additional context**
> I can help.

I hope this is a joke.

**Comment by sargent-coding** [comment]
> > It looks like you used some free Powerpoint format. If you want to see some of my art:
> > [Sargent Coding](https://www.saco.ml)
> > [Scratch](https://scratch.mit.edu/users/speedblocks)
> 
> Also that is not true, I just had a very simple design idea when this was created instead.
> Also your website was an IFrame'd wix site with the top bar hidden, so I would not consider that HTML skills.

I have this: [https://informant.micahlindley.com/](https://informant.micahlindley.com/) and this: [http://ryfelta.glitch.me/](http://ryfelta.glitch.me/)

**Comment by sargent-coding** [comment]
Also, maybe try learning the principles of design.

**Comment by Semisol** [comment]
> Also, maybe try learning the principles of design.

And not to be rude but try to learn how to code and not IFrame a Wix site.

**Comment by sargent-coding** [comment]
> > Also, maybe try learning the principles of design.
> 
> And not to be rude but try to learn how to code and not IFrame a Wix site.

I did it so I can edit it quicker. Anyways, knowing HTML5 hasn't much to do with UI design.

**Comment by ElliotDoesCode** [comment]
> > > Also, maybe try learning the principles of design.
> > 
> > 
> > And not to be rude but try to learn how to code and not IFrame a Wix site.
> 
> I did it so I can edit it quicker. Anyways, knowing HTML5 hasn't much to do with UI design.

Bro, you don't know HTML. Wix is a website builder. So as micah.

**Comment by sargent-coding** [comment]
> > > > Also, maybe try learning the principles of design.
> > > 
> > > 
> > > And not to be rude but try to learn how to code and not IFrame a Wix site.
> > 
> > 
> > I did it so I can edit it quicker. Anyways, knowing HTML5 hasn't much to do with UI design.
> 
> Bro, you don't know HTML. Wix is a website builder. So as micah.

Do you not see the other links?

**Comment by Semisol** [comment]
Can we not get off topic though, I am marking the rest as off topic if it continues.

**Comment by sargent-coding** [comment]
Alright.

I'm making a logo right now.

**Comment by sargent-coding** [comment]
So far...

![image](https://user-images.githubusercontent.com/65425469/99153671-efbc7080-2677-11eb-903b-0f62532e874d.png)

**Comment by Semisol** [comment]
seriously what is that

**Comment by sargent-coding** [comment]
im working on it

**Comment by sargent-coding** [comment]
another (yet strange) idea
![image](https://user-images.githubusercontent.com/65425469/99153795-cbad5f00-2678-11eb-91cc-7f0969aef85c.png)

**Comment by Accio1** [comment]
I don't see what is wrong with the favicon that we currently have. UI issues inmpy that there is a lack of flow, or proper design within the site itself. What needs to be added/changed with the actual site?

**Comment by sargent-coding** [comment]
So far...
![image](https://user-images.githubusercontent.com/65425469/99278023-8dd94380-27fc-11eb-9987-22fe8ef56966.png)
