### ISSUE TITLE
Idea for a better way to authenticate Scratch accounts.

### ISSUE THREAD

**Issue by sargent-coding** [ScratchVerifier/ScratchVerifier#66]
We could detect what the user's account is (like https://github.com/ScratchAddons/ScratchAddons) and then make the user push a button. Something to think about.

**Comment by sargent-coding** [comment]
ScratchAddons can detect your messages, so, of course, it can detect your username.

**Comment by Accio1** [comment]
Added the feature label and assigned people who this issue might relate to.

**Comment by Semisol** [comment]
I do not think this really will be possible, except if we made it auto comment. I do not think the ST would like that.


> ScratchAddons can detect your messages, so, of course, it can detect your username.

You can technically manipulate the data sent to the server, so would be a problem.
Except if your session was sent, then everyone would hate us.

**Comment by sargent-coding** [comment]
We could just detect what account is/was signed in and add it to a list of some sorts.

**Comment by Accio1** [comment]
> We could just detect what account is/was signed in and add it to a list of some sorts.

Like @Semisol mentioned above, the problem is getting that username. There is no straightforward way to detect who is currently logged in.

**Comment by Semisol** [comment]
> > We could just detect what account is/was signed in and add it to a list of some sorts.
> 
> Like @Semisol mentioned above, the problem is getting that username. There is no straightforward way to detect who is currently logged in.

It is possible.
BUT, the problem is verifying that the client did not lie to our servers.

> Never trust the client.

**Comment by Semisol** [comment]
Anyways the best we could do is:
Make a script that communicates with the extension verification information,
then it calls the server with the user's verification secret then marks it as valid.
But I do not see a mass implementation happening. We can't make it auto verify, then what happens when a website pretends to be another and does a request, so now they gotten a valid authorization from the user. What now?

**Comment by Kenny2github** [comment]
Keep in mind we are ultimately a server-side API. Most Scratch users do not directly interact with us, they interact with our clients. If the clients want to figure out the username automatically, they can do that, but it's up to them, not us. The Scratch users who do directly interact with us should be technically minded enough that they can deal with not having their username pre-filled in a box.

**Comment by Semisol** [comment]
> Keep in mind we are ultimately a server-side API. Most Scratch users do not directly interact with us, they interact with our clients. If the clients want to figure out the username automatically, they can do that, but it's up to them, not us. The Scratch users who do directly interact with us should be technically minded enough that they can deal with not having their username pre-filled in a box.

We still can make a script for clients interacting with users, but the problems are:
1. We can't automatically post comments, or the ST might not like it
2. The implementation has to exist on nearly all of the clients so its effectiveness is high, but not many clients would do that
3. If we don't send comments, then theres nothing we can do except a strange method of one-time login and a special token. One, the token can get leaked. Two, we try to store minimal data for every verification and for every user verified. We don't also plan to be directly interacting with users, as @Kenny2github said. If we sent session cookies you can guess what I would say next...
