### ISSUE TITLE
Be able to link Scratch accounts with Google, Github, etc.

### ISSUE THREAD

**Issue by sargent-coding** [ScratchVerifier/ScratchVerifier#68]
My idea is that you can link your Scratch/SV account to other accounts such as Google and Github. Maybe have an option to make these connections public.

**Comment by Semisol** [comment]
> My idea is that you can link your Scratch/SV account to other accounts such as Google and Github. Maybe have an option to make these connections public.

SV accounts do not exist.
We are just a service providing an API for a program to verify a user, automatically.
We do not provide support for account linking, and we only host the API.

**Comment by Semisol** [comment]
You may do this as your own project, but this is an API and not a service to link accounts, or to do other stuff.
