### ISSUE TITLE
[Backend] Database.get_client_info returns None on POST /verify/{}

### ISSUE THREAD

**Issue by Kenny2github** [ScratchVerifier/ScratchVerifier#73]
## Please provide what the bug affects.
Finishing a login.

## Please provide a step-by-step instructions for reproduction of the bug.
No clue, needs further investigation

## Please provide any screenshots, if any here.
No screenshot, just error log:
```
Traceback (most recent call last):
  File "ScratchVerifier/backend/server.py", line 87, in errors
    return await handler(request)
  File "ScratchVerifier/backend/server.py", line 301, in verified
    client_owner = (await self.db.get_client_info(client_id))['username']
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Semisol** [comment]
Can you please provide what client ID this affects?

**Comment by Semisol** [comment]
Let me quickly try to reproduce this.

**Comment by Kenny2github** [comment]
> Can you please provide what client ID this affects?

Now that #76 is merged the next time this issue occurs we'll be able to find out

**Comment by Semisol** [comment]
Okay.

**Comment by Semisol** [comment]
Cannot repro the issue BTW with my own client ID, but oh wait.

**Comment by Semisol** [comment]
Nevermind, nothing in /usage.

**Comment by Kenny2github** [comment]
As SV is pending deprecation, this will not be fixed.
